Animalink.WebApp/Controllers/AllNftsController.cs
using Animalink.Business.Nfts;
using Animalink.Data.Pocos.Nfts;
using Animalink.Services;
using Animalink.WebApp.Models.Nfts;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using WebApp.Models;

namespace Animalink.WebApp.Controllers
{
    public class AllNftsController : Controller
    {
        
        [HttpGet]
        public async Task<IActionResult> ShowAllNfts(string nftType)
        {
            //var allNftsModel = new AllNftsViewModel();
            //var allNftsBo = new AllNftsBo();
            //var nftTemplatesListOperation = await  allNftsBo.ListNftTemplates(nftType);

            //foreach (var item in template)
            //{

            //        var nftTemplateData = new NftDataPoco();

            //        nftTemplateData.Id = item.Id;
            //        nftTemplateData.NftName = item.NftName;
            //        var value = item.Price;
            //        nftTemplateData.Price = Math.Round(value, 2);
            //        nftTemplateData.NumberAvailable = item.NumberAvailable;
            //        nftTemplateData.ImageReference = item.ImageReference;
            //        allNftsModel.AllNftsDataPocos.Add(nftTemplateData);

            //}


            //var atomicAssets = new AtomicAssets();
            //var result = atomicAssets.GetTemplateById("mavp4thearte", 151352);
            //var atomicAssetsData = new Root<Services.AssetData>();
            //atomicAssetsData = JsonSerializer.Deserialize<Root<Services.AssetData>>(result.Result);
            

            var allNftsModel = new AllNftsViewModel();


            //foreach (var item in atomicAssetsData.data)
            //{
            //    var nftTemplateData = new TemplateDataPoco();

            //    nftTemplateData.AtomicAssetsTemplateId = (int)Int64.Parse(item.asset_id);
            //    nftTemplateData.NftName = item.data.name;
            //    nftTemplateData.Price = 1111;
            //    nftTemplateData.NumberAvailable = Int32.Parse(item.template.max_supply) - Int32.Parse(item.template.issued_supply);
            //    nftTemplateData.ImageReference = item.data.img;
            //    allNftsModel.AllNftsDataPocos.Add(nftTemplateData);
            //}


            return View(allNftsModel);
        }


        [HttpPost]
        public async Task<IActionResult> ShowAllNfts(AllNftsViewModel vm, string nftType)
        {
            var allNftsModel = new AllNftsViewModel();
            var allNftsBo = new TemplatesBo();
            var nftTemplatesInfo = await allNftsBo.ListFullTemplatesByType(nftType);

            foreach (var item in nftTemplatesInfo.Result)
            {
                var nftTemplateData = new FullTemplateDataPoco();

                nftTemplateData.Id = item.Id;
                nftTemplateData.Name = item.Name;
                nftTemplateData.Price = item.Price;
                nftTemplateData.NumberAvailable = item.NumberAvailable;
                nftTemplateData.ImageReference = item.ImageReference;
                allNftsModel.AllTemplatesDataPocos.Add(nftTemplateData);
            }

            return View();
        }




        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Animalink.WebApp/Controllers/PartnersController.cs
using Animalink.Business.Partners;
using Animalink.Data.Pocos.Partners;
using Animalink.WebApp.Models.Partners;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WebApp.Models;

namespace Animalink.WebApp.Controllers
{
    public class PartnersController : Controller
    {
        [HttpGet]
        public async Task<IActionResult> AllPartners()  
        {
            var allPartnersModel = new AllPartnersViewModel();
            var partnersBo = new PartnersBo();
            var allPartnersInfo = await partnersBo.ListAllPartners();

            foreach (var item in allPartnersInfo.Result)
            {
                if (!item.IsDeleted)
                {
                    var partnerData = new PartnerDataPoco();

                    partnerData.Name = item.Name;
                    partnerData.Description = item.Description;
                    partnerData.ImageReference = item.ImageReference;
                    partnerData.WebsiteURL = item.WebsiteURL;

                    allPartnersModel.PartnersDataPocos.Add(partnerData);
                }
            }

            return View(allPartnersModel);
        }


        [HttpPost]
        public async Task<IActionResult> AllPartners(AllPartnersViewModel vm)
        {
            if (ModelState.IsValid)
            {
                var allPartnersModel = new AllPartnersViewModel();
                var partnersBo = new PartnersBo();
                var allPartnersInfo = await partnersBo.ListAllPartners();

                foreach (var item in allPartnersInfo.Result)
                {
                    if (!item.IsDeleted)
                    {
                        var partnerData = new PartnerDataPoco();

                        partnerData.Name = item.Name;
                        partnerData.Description = item.Description;
                        partnerData.ImageReference = item.ImageReference;
                        partnerData.WebsiteURL = item.WebsiteURL;
                    }
                }
                return View();
            }
            else
            {
                // mecanismo de alertas de erros
                return View();
            }



        }




        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Animalink.WebApp/Controllers/UserProfileController.cs
using Animalink.Business.Users;
using Animalink.Data.Pocos.Users;
using Animalink.WebApp.Models.Users;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WebApp.Models;

namespace Animalink.WebApp.Controllers
{
    public class UserProfileController : Controller
    {
        [HttpGet]
        public async Task<IActionResult> UserInfo(Guid userId)
        {
            userId = new Guid("93CE26A3-6E6E-4349-988C-24EB83649E8F");

            var userModel = new UserProfileViewModel();
            var userBo = new UsersBo();
            var userInfo = await userBo.GetUserInfo(userId);

            var userData = new UserDataPoco();
            userData.Id = userInfo.Result.Id;
            userData.UserName = userInfo.Result.UserName;
            userData.ImageReference = userInfo.Result.ImageReference;

            userModel.UserDataPoco = userData;

            return View(userModel);
        }


        [HttpPost]
        public async Task<IActionResult> Userinfo(UserProfileViewModel vm, Guid userId)
        {
   
            if (ModelState.IsValid)
            {
                var userModel = new UserProfileViewModel();
                var userBo = new UsersBo();
                var userInfo = await userBo.GetUserInfo(userId);

                var userData = new UserDataPoco();
                userData.Id = userInfo.Result.Id;
                userData.UserName = userInfo.Result.UserName;
                userData.ImageReference = userInfo.Result.ImageReference;

                userModel.UserDataPoco = userData;

                return View(userModel);
            }
            else
            {
                // mecanismo de alertas de erros
                return View();
            }
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Animalink.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

@*---Head---*@
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Animalink</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @RenderSection("Styles", required: false)
</head>

@*---Body---*@
<body>

    @*---Body Header---*@
    <header>

            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light box-shadow">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Animalink</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="AllNfts" asp-action="ShowAllNfts">Buy NFTs</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Partners" asp-action="AllPartners">Partners</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="UserProfile" asp-action="UserInfo">User Profile</a> 
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>

    </header>

    @*---Body Content---*@
    <div> @*class="container"*@
        <main role="main">  @*class="pb-1"*@
            @RenderBody()
        </main>
    </div>

    @*---Footer---*@
    <footer class="text-center text-lg-start">

        <div class="text-center p-3">
            &copy; 2021 - WebApp - <a class="text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>

    </footer>


    @*---Scripts---*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>