Animalink.AdminWebApp/Controllers/TemplatesController.cs
using Animalink.AdminWebApp.Models;
using Animalink.AdminWebApp.Models.Creator;
using Animalink.AdminWebApp.Models.Templates;
using Animalink.Business.Base;
using Animalink.Business.Nfts;
using Animalink.Data;
using Animalink.Data.Context;
using Animalink.Data.Pocos.Nfts;
using Animalink.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;

namespace Animalink.AdminWebApp.Controllers
{
    public class TemplatesController : Controller
    {
        // test
        [HttpGet]
        public ActionResult ChosenDropDown()
        {
            AnimalinkDBContext db = new AnimalinkDBContext();

            Filters objCustomer = new Filters();
            objCustomer.GetTemplateTypeList = db.TemplateTypes.Select(x => new Filters {TemplateType = x.Name }).ToList();
            objCustomer.GetRarityList = db.Rarities.Select(x => new Filters {Rarity = x.Name }).ToList();
            objCustomer.GetSchemaList = db.Schemas.Select(x => new Filters {Schema = x.Name }).ToList();
            objCustomer.GetCollectionList = db.Collections.Select(x => new Filters {Collection = x.Name }).ToList();

            return View(objCustomer);
        }


        [HttpPost]
        public ActionResult ChosenDropDown(Filters objCustomer)
        {


            return RedirectToAction(nameof(ChosenDropDown));
        }
        //---



        #region new Index

        [HttpGet]
        public async Task<IActionResult> Index(string templateName, Guid? templateTypeId, Guid? rarityId, Guid? schemaId, Guid? collectionId)
        {
            AnimalinkDBContext db = new AnimalinkDBContext();
            var templatesModel = new TemplatesViewModel();

            templatesModel.GetTemplateNameList = db.Templates.Select(x => new TemplatesViewModel { TemplateName = x.Name }).ToList();
            templatesModel.GetTemplateTypeList = db.TemplateTypes.Select(x => new TemplatesViewModel { TemplateType = x.Name }).ToList();
            templatesModel.GetRarityList = db.Rarities.Select(x => new TemplatesViewModel { Rarity = x.Name }).ToList();
            templatesModel.GetSchemaList = db.Schemas.Select(x => new TemplatesViewModel { Schema = x.Name }).ToList();
            templatesModel.GetCollectionList = db.Collections.Select(x => new TemplatesViewModel { Collection = x.Name }).ToList();


            var atomicAssets = new AtomicAssets();
            var resultTemplate = atomicAssets.GetAllTemplatesInCollection("mavp4thearte");
            var atomicAssetsData = new Root<List<TemplateData>>();
            atomicAssetsData = JsonSerializer.Deserialize<Root<List<TemplateData>>>(resultTemplate.Result);


            var templatesBo = new TemplatesBo();
            var templatesListOperation = await templatesBo.ListFullTemplatesByFilters(templateName, templateTypeId, rarityId, schemaId, collectionId);

            if (!templatesListOperation.Success)
            {
                return null;
            }
            else
            {

                foreach (var item in templatesListOperation.Result)
                {

                    var templateData = new FullTemplateDataPoco();

                    foreach (var atomicItem in atomicAssetsData.data)
                    {
                        if ((int)Int32.Parse(atomicItem.template_id) == item.AtomicAssetsId)
                        {
                            templateData.AtomicAssetsId = (int)Int32.Parse(atomicItem.template_id);
                        }

                        if (atomicItem.MaxSupply != null && atomicItem.IssuedSupply != null)
                            templateData.NumberAvailable = atomicItem.MaxSupply.Value - atomicItem.IssuedSupply.Value;
                        }

                    templateData.Id = item.Id;
                    templateData.Name = item.Name;
                    templateData.Schema = item.Schema;
                    templateData.Collection = item.Collection;
                    templateData.Description = item.Description;
                    templateData.Price = item.Price;

                    templatesModel.AllTemplatesDataPocos.Add(templateData);
                }

                return View(templatesModel);
            }
        }


        [HttpPost]
        public async Task<IActionResult> Index(TemplatesViewModel vm)
        {

            var atomicAssets = new AtomicAssets();
            var resultTemplate = atomicAssets.GetAllTemplatesInCollection("mavp4thearte");
            var atomicAssetsData = new Root<List<TemplateData>>();
            atomicAssetsData = JsonSerializer.Deserialize<Root<List<TemplateData>>>(resultTemplate.Result);

            var templatesModel = new TemplatesViewModel();

            var templatesBo = new TemplatesBo();
            var templatesListOperation = await templatesBo.ListFullTemplatesByFilters(vm.TemplateName, vm.TemplateTypeId, vm.RarityId, vm.SchemaId, vm.CollectionId);

            if (!templatesListOperation.Success)
            {
                return null;
            }
            else
            {

                foreach (var item in templatesListOperation.Result)
                {

                    var templateData = new FullTemplateDataPoco();

                    var atomicItem = atomicAssetsData.data.SingleOrDefault(i => Int32.Parse(i.template_id) == item.AtomicAssetsId);
                    if (atomicItem == null) continue;

                    templateData.AtomicAssetsId = (int)Int32.Parse(atomicItem.template_id);

                    if (atomicItem.MaxSupply != null && atomicItem.IssuedSupply != null)
                    {
                        templateData.NumberAvailable = atomicItem.MaxSupply.Value - atomicItem.IssuedSupply.Value;
                    }

                    templateData.Id = item.Id;
                    templateData.Name = item.Name;
                    templateData.Schema = item.Schema;
                    templateData.Collection = item.Collection;
                    templateData.Description = item.Description;
                    templateData.Price = item.Price;

                    templatesModel.AllTemplatesDataPocos.Add(templateData);

                }

                return View(templatesModel);
            }
        }


        #endregion


        #region old Index------

        //[HttpGet]
        //public async Task<IActionResult> Index(string nftType)
        //{
        //    var atomicAssets = new AtomicAssets();
        //    var resultTemplate = atomicAssets.GetAllTemplatesInCollection("mavp4thearte");
        //    var atomicAssetsData = new Root<List<TemplateData>>();
        //    atomicAssetsData = JsonSerializer.Deserialize<Root<List<TemplateData>>>(resultTemplate.Result);
        //    var templatesModel = new TemplatesViewModel();

        //    var templatesBo = new TemplatesBo();
        //    var templatesListOperation = await templatesBo.ListFullTemplatesByType(nftType);

        //    if (!templatesListOperation.Success)
        //    {
        //        return null;
        //    }
        //    else
        //    {

        //        foreach (var item in templatesListOperation.Result)
        //        {

        //            var templateData = new FullTemplateDataPoco();

        //            foreach (var atomicItem in atomicAssetsData.data)
        //            {
        //                if ((int)Int32.Parse(atomicItem.template_id) == item.AtomicAssetsId)
        //                {
        //                    templateData.AtomicAssetsId = (int)Int32.Parse(atomicItem.template_id);
        //                    if(atomicItem.MaxSupply != null && atomicItem.IssuedSupply != null)
        //                        templateData.NumberAvailable = atomicItem.MaxSupply.Value - atomicItem.IssuedSupply.Value;

        //                    templateData.Id = item.Id;
        //                    templateData.Name = item.Name;
        //                    templateData.Schema = item.Schema;
        //                    templateData.Collection = item.Collection;
        //                    templateData.Description = item.Description;
        //                    templateData.Price = item.Price;

        //                    templatesModel.AllTemplatesDataPocos.Add(templateData);
        //                }
        //            }
        //        }

        //        return View(templatesModel);
        //    }
        //}

        //[HttpPost]
        //public async Task<IActionResult> Index(TemplatesViewModel searchByObj)
        //{
        //    var search = searchByObj.SearchBy[1];

        //    var atomicAssets = new AtomicAssets();
        //    var resultTemplate = atomicAssets.GetAllTemplatesInCollection("mavp4thearte");
        //    var atomicAssetsData = new Root<List<TemplateData>>();
        //    atomicAssetsData = JsonSerializer.Deserialize<Root<List<TemplateData>>>(resultTemplate.Result);
        //    var templatesModel = new TemplatesViewModel();

        //    var templatesBo = new TemplatesBo();
        //    var templatesListOperation = await templatesBo.GetFullTemplatesByName(search);

        //    if (!templatesListOperation.Success)
        //    {
        //        return null;
        //    }
        //    else
        //    {

        //        foreach (var item in templatesListOperation.Result)
        //        {

        //            var templateData = new FullTemplateDataPoco();

        //            var atomicItem = atomicAssetsData.data.SingleOrDefault(i => Int32.Parse(i.template_id) == item.AtomicAssetsId);
        //            if (atomicItem == null) continue;

        //            templateData.AtomicAssetsId = (int)Int32.Parse(atomicItem.template_id);
        //            if (atomicItem.MaxSupply != null && atomicItem.IssuedSupply != null)

Animalink.AdminWebApp/Views/Templates/AddAnimal.cshtml
@model Animalink.AdminWebApp.Models.Creator.AnimalViewModel

@{
    ViewData["Title"] = "Add Animal";
}

@section Styles{
    <link rel="stylesheet" href="~/css/" />
}


@*---Header---*@
<section>
    <br />
    <br />
    <nav class="nav nav-pills flex-column flex-sm-row">
        <a class="flex-sm-fill text-sm-center nav-link" aria-current="page" asp-controller="Templates" asp-action="Index">Templates</a>
        <a class="flex-sm-fill text-sm-center nav-link" aria-current="page" asp-controller="Templates" asp-action="CreatorPage">Creator</a>
    </nav>
    <br />
    <br />
</section>


@*---Template ---*@

<section class="AddAnimal">

    <div id="template" class="card">
        <div class="card-body">
            <div class="ml-5 mr-5">
                <form asp-action="AddAnimal">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group col-lg-3 col-md-6 col-lg-12">

                        <label asp-for="@Model.Name" class="control-label"></label>
                        <input asp-for="@Model.Name" class="form-control lg-5" />
                        <span asp-validation-for="@Model.Name" class="text-danger"></span>

                        <label asp-for="@Model.Species" class="control-label"></label>
                        <input asp-for="@Model.Species" class="form-control lg-5" />
                        <span asp-validation-for="@Model.Species" class="text-danger"></span>

                        <label asp-for="@Model.Habitat" class="control-label"></label>
                        <input asp-for="@Model.Habitat" class="form-control lg-5" />
                        <span asp-validation-for="@Model.Habitat" class="text-danger"></span>

                        <label asp-for="@Model.Taxonomy" class="control-label"></label>
                        <input asp-for="@Model.Taxonomy" class="form-control lg-5" />
                        <span asp-validation-for="@Model.Taxonomy" class="text-danger"></span>

                        <label asp-for="@Model.IUCN" class="control-label"></label>
                        <input asp-for="@Model.IUCN" class="form-control lg-5" />
                        <span asp-validation-for="@Model.IUCN" class="text-danger"></span>

                        <label asp-for="@Model.IUCNAcronym" class="control-label"></label>
                        <input asp-for="@Model.IUCNAcronym" class="form-control lg-5" />
                        <span asp-validation-for="@Model.IUCNAcronym" class="text-danger"></span>

                    </div>

                    <div class="form-group ml-4">
                        <input type="submit" value="Create" class="btn btn-primary" />
                        <a class="btn btn-primary" asp-controller="Templates" asp-action="CreatorPage">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <br />

</section>

Animalink.AdminWebApp/Views/Templates/AddTemplateType.cshtml
@model Animalink.AdminWebApp.Models.Creator.TemplateTypeViewModel

@{
    ViewData["Title"] = "Add Template Type";
}

@section Styles{
    <link rel="stylesheet" href="~/css/" />
}


@*---Header---*@
<section>
    <br />
    <br />
    <nav class="nav nav-pills flex-column flex-sm-row">
        <a class="flex-sm-fill text-sm-center nav-link" aria-current="page" asp-controller="Templates" asp-action="Index">Templates</a>
        <a class="flex-sm-fill text-sm-center nav-link" aria-current="page" asp-controller="Templates" asp-action="CreatorPage">Creator</a>
    </nav>
    <br />
    <br />
</section>



<section class="AddTemplateType">

    <div id="template" class="card">
        <div class="card-body">
            <div class="ml-5 mr-5">
                <form asp-action="AddTemplateType">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group col-lg-3 col-md-6 col-lg-12">

                        <label asp-for="@Model.Name" class="control-label"></label>
                        <input asp-for="@Model.Name" class="form-control lg-5" />
                        <span asp-validation-for="@Model.Name" class="text-danger"></span>

                    </div>

                    <div class="form-group ml-4">
                        <input type="submit" value="Create" class="btn btn-primary" />
                        <a class="btn btn-primary" asp-controller="Templates" asp-action="CreatorPage">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <br />

</section>

Animalink.AdminWebApp/Views/Templates/ChosenDropDown.cshtml
@model Animalink.AdminWebApp.Models.Templates.Filters

@{
    ViewBag.Title = "ChosenDropDown";
}

<h2>ChosenDropDown</h2>
<link rel="stylesheet" href="/lib/chosen_v1.8.7/chosen.css" />
<script src="~/lib/chosen_v1.8.7/chosen.jquery.js"></script>

@using (Html.BeginForm())
{
    @Html.DropDownListFor(x => x.TemplateTypeList,
    Model.GetTemplateTypeList.Select(x => new SelectListItem { Text = x.TemplateType, Value = x.TemplateType.ToString() }),
    new { @class = "form-control chosen-select", @multiple = true });

    @Html.DropDownListFor(x => x.RarityList,
    Model.GetRarityList.Select(x => new SelectListItem { Text = x.Rarity, Value = x.Rarity }),
    new { @class = "form-control chosen-select", @multiple = true });

    @Html.DropDownListFor(x => x.CollectionList,
    Model.GetCollectionList.Select(x => new SelectListItem { Text = x.Collection, Value = x.Collection }),
    new { @class = "form-control chosen-select", @multiple = true });


    <input type="submit" name="name" value="Submit" />

}

<script>

    $('.chosen-select').chosen();

</script>

Animalink.AdminWebApp/Views/Templates/CreateTemplate.cshtml
@model Animalink.AdminWebApp.Models.Templates.EditTemplateViewModel

@{
    ViewData["Title"] = "Template Creator";
}


@section Styles{
    <link rel="stylesheet" href="~/css/TemplateCreatorStyle.css" />
}



@*---Header---*@
<section>
    <br />
    <br />
    <nav class="nav nav-pills flex-column flex-sm-row">
        <a class="flex-sm-fill text-sm-center nav-link" aria-current="page" asp-controller="Templates" asp-action="Index">Templates</a>
        <a class="flex-sm-fill text-sm-center nav-link active" aria-current="page" asp-controller="Templates" asp-action="CreatorPage">Creator</a>
    </nav>
    <br />
    <br />
</section>


@*---Template ---*@

  
<section class="NftInfo">


    <div id="template" class="card">
        <div class="card-body">
            <div class="ml-5 mr-5">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group col-lg-3 col-md-6 col-lg-12">

                        <label asp-for="@Model.Name" class="control-label"></label>
                        <input asp-for="@Model.Name" class="form-control lg-5" />
                        <span asp-validation-for="@Model.Name" class="text-danger"></span>

                        <label asp-for="@Model.Description" class="control-label"></label>
                        <input asp-for="@Model.Description" class="form-control lg-5" />
                        <span asp-validation-for="@Model.Description" class="text-danger"></span>

                        <label asp-for="@Model.Collection" class="control-label"></label>
                        <input asp-for="@Model.Collection" class="form-control lg-5" />
                        <span asp-validation-for="@Model.Collection" class="text-danger"></span>

                        <label asp-for="@Model.Schema" class="control-label"></label>
                        <input asp-for="@Model.Schema" class="form-control lg-5" />
                        <span asp-validation-for="@Model.Schema" class="text-danger"></span>

                        <label asp-for="@Model.Price" class="control-label"></label>
                        <input asp-for="@Model.Price" class="form-control lg-5" />
                        <span asp-validation-for="@Model.Price" class="text-danger"></span>

                        <label asp-for="@Model.MaxSupply" class="control-label"></label>
                        <input asp-for="@Model.MaxSupply" class="form-control lg-5" />
                        <span asp-validation-for="@Model.MaxSupply" class="text-danger"></span>

                        <label asp-for="@Model.IsPublished" class="control-label"></label>
                        <input asp-for="@Model.IsPublished" class="form-control lg-5" />
                        <span asp-validation-for="@Model.IsPublished" class="text-danger"></span>

                        <label asp-for="@Model.IsTransferable" class="control-label"></label>
                        <input asp-for="@Model.IsTransferable" class="form-control lg-5" />
                        <span asp-validation-for="@Model.IsTransferable" class="text-danger"></span>

                        <label asp-for="@Model.IsBurnable" class="control-label"></label>
                        <input asp-for="@Model.IsBurnable" class="form-control lg-5" />
                        <span asp-validation-for="@Model.IsBurnable" class="text-danger"></span>

                        <label asp-for="@Model.TemplateType" class="control-label"></label>
                        <input asp-for="@Model.TemplateType" class="form-control lg-5" />
                        <span asp-validation-for="@Model.TemplateType" class="text-danger"></span>

                        <label asp-for="@Model.Rarity" class="control-label"></label>
                        <input asp-for="@Model.Rarity" class="form-control lg-5" />
                        <span asp-validation-for="@Model.Rarity" class="text-danger"></span>

                        <label asp-for="@Model.ImageReference" class="control-label"></label>
                        <input asp-for="@Model.ImageReference" class="form-control lg-5" />
                        <span asp-validation-for="@Model.ImageReference" class="text-danger"></span>



                    </div>

                    <div class="form-group ml-4">
                        <input type="submit" value="Create" class="btn btn-primary" />
                        <a class="btn btn-primary" asp-controller="Templates" asp-action="Index">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>












    <!--<div class="container">
        <div class="row">

            <div class="col">
                <img src="" class="img-fluid" alt="Image" style="width:100%;height:100%;" />
            </div>

            <div class="col" id="Attributes" style="width:100%;height:70%;">
                <h3 id="AttributesTitle">Attributes</h3>
                <p><b>Name: </b><input type="text" class="form-control" placeholder=""></p>
                <p><b>Type: </b><input type="text" class="form-control" placeholder=""></p>
                <p><b>Rarity: </b><input type="text" class="form-control" placeholder=""></p>
                <p><b>Level: </b><input type="text" class="form-control" placeholder=""></p>-->

                @*<p>Species: <input type="text" class="form-control" placeholder=""></p>
                    <p>Taxonomy: <input type="text" class="form-control" placeholder=""></p>
                    <p>Habitat: <input type="text" class="form-control" placeholder=""></p>
                    <p>IUCN: <input type="text" class="form-control" placeholder=""></p>*@

                <!--<p><b>Schema: </b><input type="text" class="form-control" placeholder=""></p>
                <p><b>Collection: </b><input type="text" class="form-control" placeholder=""></p>
                <p><b>Max Supply: </b><input type="text" class="form-control" placeholder=""></p>

                <p><b>Is Burnable: </b><input type="text" class="form-control" placeholder=""></p>
                <p><b>Is Tranferable: </b><input type="text" class="form-control" placeholder=""></p>
                <p><b>Image Reference: </b><input type="text" class="form-control" placeholder=""></p>

            </div>

            <div class="col">

            </div>

        </div>

        <div class="row">
            <div class="col">
                <br />
                <br />
                <br />
            </div>
        </div>

        <div class="row">

            <div class="col" id="Description">
                <h2>Description</h2>
                <p>
                    <input type="text" class="form-control" placeholder="">
                </p>
            </div>

            <div class="col">

            </div>

            <div class="col" id="Buy">
                <p>Price: <input type="text" class="form-control" placeholder=""> </p>
            </div>

        </div>
    </div>-->

    <br />
    <a class="flex-sm-fill text-sm-center nav-link" aria-current="page" asp-controller="Nft" asp-action="Create">Create Template</a>
</section>

        @*Event Template*@

        <!--<section class="NftInfo">

            <div class="container">
                <div class="row">

                    <div class="col">
                        <img src="~/Media/Frog_mockup.png" class="img-fluid" alt="Image" style="width:100%;height:100%;" />
                    </div>

                    <div class="col" id="Attributes" style="width:100%;height:70%;">
                        <h3 id="AttributesTitle">Attributes</h3>
                        <p><b>Name: </b><input type="text" class="form-control" placeholder=""></p>
                        <p><b>Type: </b><input type="text" class="form-control" placeholder=""></p>
                        <p><b>Rarity: </b><input type="text" class="form-control" placeholder=""></p>
                        <p><b>Level: </b><input type="text" class="form-control" placeholder=""></p>

                        <p><b>Schema: </b><input type="text" class="form-control" placeholder=""></p>
                        <p><b>Collection: </b><input type="text" class="form-control" placeholder=""></p>
                        <p><b>Max Supply: </b><input type="text" class="form-control" placeholder=""></p>
                        <p><b>Number Available: </b><input type="text" class="form-control" placeholder=""></p>--> @*api*@
                        <!--<p><b>Is Burnable: </b><input type="text" class="form-control" placeholder=""></p>
                        <p><b>Is Tranferable: </b><input type="text" class="form-control" placeholder=""></p>
                        <p><b>Image Reference: </b><input type="text" class="form-control" placeholder=""></p>
                    </div>

                    <div class="col">
                        3 of 3
                    </div>

                </div>

                <div class="row">
                    <div class="col">
                        <br />
                        <br />
                        <br />
                    </div>
                </div>

                <div class="row">

                    <div class="col" id="Description">
                        <h2>Description</h2>
                        <p>
                            <input type="text" class="form-control" placeholder="">
                        </p>
                    </div>

                    <div class="col">
                        2 of 3 (wider)
                    </div>

                    <div class="col" id="Buy">
                        <p>Price: <input type="text" class="form-control" placeholder=""> </p>
                    </div>

                </div>
            </div>

            <br />
        </section>-->

Animalink.AdminWebApp/Views/Templates/CreatorPage.cshtml
@{
    ViewData["Title"] = "Creator Page";
}

@section Styles{
    <link rel="stylesheet" href="~/css/CreatorPageStyle.css" /> }


<section>
    <div class="btn-group" role="group">
        <a type="button" class="btn btn-primary" asp-controller="Templates" asp-action="Index">Templates</a>
        <a type="button" class="btn btn-primary" asp-controller="Templates" asp-action="CreatorPage">Creator</a>
    </div>
</section>


<section>

    <div class="container">

        <div class="row">
            <div class="col">
                <br />
                <br />
            </div>
            <div class="col">

            </div>
            <div class="col">

            </div>
        </div>

        <div class="row">

            <div class="col">
                <div class="card bg-c-green order-card">
                    <a asp-controller="Templates" asp-action="CreateTemplate">
                        <div class="card-block">
                            <h2 class="text-center"><span>Template Creator</span></h2>
                        </div>
                    </a>
                </div>
                <br />
                <br />
            </div>

        </div>


        <div class="row">

            <div class="col">
                <div class="card bg-c-green order-card">
                    <a asp-controller="Templates" asp-action="AddAnimal">
                        <div class="card-block">
                            <h2 class="text-center"><span>Add Animal</span></h2>
                        </div>
                    </a>
                </div>
            </div>

            <div class="col">
                <div class="card bg-c-green order-card">
                    <a asp-controller="Templates" asp-action="AddTemplateType">
                        <div class="card-block">
                            <h2 class="text-center"><span>Add Type</span></h2>
                        </div>
                    </a>
                </div>
            </div>

            <div class="col">
                <div class="card bg-c-green order-card">
                    <a asp-controller="Templates" asp-action="ChosenDropDown">
                        <div class="card-block">
                            <h2 class="text-center"><span>Add Rarity</span></h2>
                        </div>
                    </a>
                </div>
            </div>

            <div class="col">
                <div class="card bg-c-green order-card">
                    <a asp-controller="Templates" asp-action="ChosenDropDown">
                        <div class="card-block">
                            <h2 class="text-center"><span>Add Schema</span></h2>
                        </div>
                    </a>
                </div>
            </div>

            <div class="col">
                <div class="card bg-c-green order-card">
                    <a asp-controller="Templates" asp-action="ChosenDropDown">
                        <div class="card-block">
                            <h2 class="text-center"><span>Add Collection</span></h2>
                        </div>
                    </a>
                </div>
            </div>

        </div>


        <div class="row">
            <div class="col">

            </div>
            <div class="col">

            </div>
            <div class="col">

            </div>
        </div>

    </div>

</section>