Animalink.WebApp/Models/Nfts/AllNftsViewModel.cs
using Animalink.Data.Pocos.Nfts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Animalink.WebApp.Models.Nfts
{
    public class AllNftsViewModel
    {
        public List<FullTemplateDataPoco> AllTemplatesDataPocos { get; set; }

        public AllNftsViewModel()
        {
            AllTemplatesDataPocos = new List<FullTemplateDataPoco>();
        }


    }
}

Animalink.WebApp/Controllers/AllNftsController.cs
using Animalink.Business.Nfts;
using Animalink.Data.Pocos.Nfts;
using Animalink.Services;
using Animalink.WebApp.Models.Nfts;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using WebApp.Models;

namespace Animalink.WebApp.Controllers
{
    public class AllNftsController : Controller
    {
        
        [HttpGet]
        public async Task<IActionResult> ShowAllNfts(string nftType)
        {
            //var allNftsModel = new AllNftsViewModel();
            //var allNftsBo = new AllNftsBo();
            //var nftTemplatesListOperation = await  allNftsBo.ListNftTemplates(nftType);

            //foreach (var item in template)
            //{

            //        var nftTemplateData = new NftDataPoco();

            //        nftTemplateData.Id = item.Id;
            //        nftTemplateData.NftName = item.NftName;
            //        var value = item.Price;
            //        nftTemplateData.Price = Math.Round(value, 2);
            //        nftTemplateData.NumberAvailable = item.NumberAvailable;
            //        nftTemplateData.ImageReference = item.ImageReference;
            //        allNftsModel.AllNftsDataPocos.Add(nftTemplateData);

            //}


            //var atomicAssets = new AtomicAssets();
            //var result = atomicAssets.GetTemplateById("mavp4thearte", 151352);
            //var atomicAssetsData = new Root<Services.AssetData>();
            //atomicAssetsData = JsonSerializer.Deserialize<Root<Services.AssetData>>(result.Result);
            

            var allNftsModel = new AllNftsViewModel();


            //foreach (var item in atomicAssetsData.data)
            //{
            //    var nftTemplateData = new TemplateDataPoco();

            //    nftTemplateData.AtomicAssetsTemplateId = (int)Int64.Parse(item.asset_id);
            //    nftTemplateData.NftName = item.data.name;
            //    nftTemplateData.Price = 1111;
            //    nftTemplateData.NumberAvailable = Int32.Parse(item.template.max_supply) - Int32.Parse(item.template.issued_supply);
            //    nftTemplateData.ImageReference = item.data.img;
            //    allNftsModel.AllNftsDataPocos.Add(nftTemplateData);
            //}


            return View(allNftsModel);
        }


        [HttpPost]
        public async Task<IActionResult> ShowAllNfts(AllNftsViewModel vm, string nftType)
        {
            var allNftsModel = new AllNftsViewModel();
            var allNftsBo = new TemplatesBo();
            var nftTemplatesInfo = await allNftsBo.ListFullTemplatesByType(nftType);

            foreach (var item in nftTemplatesInfo.Result)
            {
                var nftTemplateData = new FullTemplateDataPoco();

                nftTemplateData.Id = item.Id;
                nftTemplateData.Name = item.Name;
                nftTemplateData.Price = item.Price;
                nftTemplateData.NumberAvailable = item.NumberAvailable;
                nftTemplateData.ImageReference = item.ImageReference;
                allNftsModel.AllTemplatesDataPocos.Add(nftTemplateData);
            }

            return View();
        }




        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Animalink.WebApp/Controllers/NftController.cs
using Animalink.Business.Nfts;
using Animalink.Data.Pocos.Nfts;
using Animalink.WebApp.Models.Nfts;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WebApp.Models;

namespace Animalink.WebApp.Controllers
{
    public class NftController : Controller
    {
        [HttpGet("Id")]
        public async Task<IActionResult> NftInfo(Guid nftId)
        {
            var nftModel = new NftViewModel();
            var allNftsBo = new TemplatesBo();
            var nftTemplateListOperation = await allNftsBo.GetFullTemplateById(nftId);
            var template = nftTemplateListOperation.Result;

                var nftTemplateData = new FullTemplateDataPoco();

                nftTemplateData.Id = template.Id;
                nftTemplateData.Name = template.Name;
                nftTemplateData.TemplateType = template.TemplateType;
                nftTemplateData.Rarity = template.Rarity;
                nftTemplateData.RarityLevel = template.RarityLevel;
                nftTemplateData.Species = template.Species;
                nftTemplateData.Taxonomy = template.Taxonomy;
                nftTemplateData.Habitat = template.Habitat;
                nftTemplateData.IUCN = template.IUCN;
                nftTemplateData.IUCNAcronym = template.IUCNAcronym;
                nftTemplateData.Schema = template.Schema;
                nftTemplateData.Collection = template.Collection;
                nftTemplateData.MaxSupply = template.MaxSupply;
                nftTemplateData.NumberAvailable = template.NumberAvailable;
                nftTemplateData.IsBurnable = template.IsBurnable;
                nftTemplateData.IsTransferable = template.IsTransferable;
                nftTemplateData.ImageReference = template.ImageReference;
                nftTemplateData.Description = template.Description;

                var value = template.Price;
                nftTemplateData.Price = Math.Round(value, 2);
                
                

                nftModel.NftDataPocos.Add(nftTemplateData);

            return View(nftModel);

        }
            
        


        [HttpPost]
        public async Task<IActionResult> ShowNftInfo(AllNftsViewModel vm, Guid nftId)
        {
            var nftModel = new NftViewModel();
            var allNftsBo = new TemplatesBo();
            var nftTemplateListOperation = await allNftsBo.GetFullTemplateById(nftId);
            var template = nftTemplateListOperation.Result;


                var nftTemplateData = new FullTemplateDataPoco();

                nftTemplateData.Id = template.Id;
                nftTemplateData.Name = template.Name;
                var value = template.Price;
                nftTemplateData.Price = Math.Round(value, 2);
                nftTemplateData.NumberAvailable = template.NumberAvailable;
                nftTemplateData.ImageReference = template.ImageReference;
                nftModel.NftDataPocos.Add(nftTemplateData);

            return View(nftModel);

        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Animalink.WebApp/Views/AllNfts/ShowAllNfts.cshtml
@model Animalink.WebApp.Models.Nfts.AllNftsViewModel
@{
    ViewData["Title"] = "Buy NFT";
}

@section Styles{
    <link rel="stylesheet" href="~/css/AllNftsStyle.css"/> }      



@*---Sorting---*@
<section class="Sorting" style="padding-left: 20px;"> @*---change to css---*@
    <p>Sorting</p>
    <a asp-controller="AllNfts" asp-action="ShowAllNfts" asp-route-nftType="">All</a>
    <a asp-controller="AllNfts" asp-action="ShowAllNfts" asp-route-nftType="Animal">Animals</a>
    <a asp-controller="AllNfts" asp-action="ShowAllNfts" asp-route-nftType="Event">Events</a>
    <br />
    <br />
</section>


@*---All NFTs---*@
<section class="AllNFTs">
    <h3>All NFTs</h3>

    <div class="card-group">

        @foreach (var item in Model.AllTemplatesDataPocos)
        {
            <div class="col-2">
                <div class="card">
                    <img class="card-img-top" src="~/Media/Frog_mockup.png" alt="Image">
                    <div class="card-body">
                        <p class="card-text">Name: @item.NftName <br /> Available: @item.NumberAvailable</p>
                        <a href="#" class="btn btn-primary">@item.Price</a>

                        <a class="btn btn-primary" asp-controller="Nft" asp-action="NftInfo" asp-route-nftId="@item.Id">Buy</a>

                    </div>
                </div>
            </div>
        }

    </div>
    <br />
</section>


@*---Almost Soldout NFTs---*@
<section class="AlmostGone">
    <h3>Almost Gone NFTs</h3>

    <div class="card-group">

        @foreach (var item in Model.AllTemplatesDataPocos)
        {
            <div class="card">
                <img class="card-img-top" src="~/Media/Frog_mockup.png" alt="Image" >
                <div class="card-body">
                    <p class="card-text">Name: @item.NftName <br /> Available: @item.NumberAvailable</p>
                    <a href="#" class="btn btn-primary">@item.Price</a>
                    <a href="#" class="btn btn-primary">Buy</a>
                </div>
            </div>
        }

    </div>

    <br />
</section>